### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Cvjark** [rockcarry/ffjpeg#52]
### sample file 
[id8_memory_leak.zip](https://github.com/rockcarry/ffjpeg/files/9053199/id8_memory_leak.zip)

### command to reproduce
`./ffjpeg -d [sample file]`

### execute info
```
usrc overflow

=================================================================
==16225==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4ae760 in malloc /home/bupt/Desktop/tools/llvm-12.0.1/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x4f8ddf in jfif_decode /home/bupt/Desktop/ffjpeg/src/jfif.c:404:23
    #2 0x4f4495 in main /home/bupt/Desktop/ffjpeg/src/ffjpeg.c:24:9
    #3 0x7f9807bedc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4ae760 in malloc /home/bupt/Desktop/tools/llvm-12.0.1/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x4f8cfe in jfif_decode /home/bupt/Desktop/ffjpeg/src/jfif.c:404:23
    #2 0x4f4495 in main /home/bupt/Desktop/ffjpeg/src/ffjpeg.c:24:9
    #3 0x7f9807bedc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4ae760 in malloc /home/bupt/Desktop/tools/llvm-12.0.1/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x4f9ea7 in jfif_decode /home/bupt/Desktop/ffjpeg/src/jfif.c:445:21
    #2 0x4f4495 in main /home/bupt/Desktop/ffjpeg/src/ffjpeg.c:24:9
    #3 0x7f9807bedc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4ae760 in malloc /home/bupt/Desktop/tools/llvm-12.0.1/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x4f9e6b in jfif_decode /home/bupt/Desktop/ffjpeg/src/jfif.c:444:21
    #2 0x4f4495 in main /home/bupt/Desktop/ffjpeg/src/ffjpeg.c:24:9
    #3 0x7f9807bedc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

Direct leak of 1 byte(s) in 1 object(s) allocated from:
    #0 0x4ae760 in malloc /home/bupt/Desktop/tools/llvm-12.0.1/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
    #1 0x4f9e25 in jfif_decode /home/bupt/Desktop/ffjpeg/src/jfif.c:443:21
    #2 0x4f4495 in main /home/bupt/Desktop/ffjpeg/src/ffjpeg.c:24:9
    #3 0x7f9807bedc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: 515 byte(s) leaked in 5 allocation(s).
```

**Comment by wnpllrzodiac** [comment]
Just a toy, cannot expect too much.
